### ISSUE TITLE
Implement the JSON reporter

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#109]
Right now, the CLI prints the diagnostics in a human-readable format, which is nice, but not scriptable. We should add a new option `--reporter` to the CLI (no need for a shorthand) that accepts options `pretty` (default) or `json`. When `--reporter json`, the output should be pretty-printed JSON, no color. Basically, just dump the whole diagnostics array as it is.

**Comment by Benjamin-Frost** [comment]
Hi @illright, I'm interested in contributing to this project for Hacktoberfest and would love to work on this issue. Could I take a shot at it?

**Comment by illright** [comment]
Hi @Benjamin-Frost, that's great! Yes, please go ahead, and feel free to ask any questions here if you get stuck :)
