### ISSUE TITLE
Steiger gives you "unknown" when you ask for its version

### ISSUE THREAD

**Issue by daniilsapa** [feature-sliced/steiger#127]
<img width="497" alt="Screenshot 2024-11-16 at 14 56 01" src="https://github.com/user-attachments/assets/80ce485a-c48a-4d55-a067-c41b61a0afc2">

**Comment by illright** [comment]
Lol yeah that's janky :D

What would also be nice here is to print the versions of all plugins used in the current config.

**Comment by daniilsapa** [comment]
Yes, I agree, good idea
