### ISSUE TITLE
insignificant-slice rule does not work correctly

### ISSUE THREAD

**Issue by EgorEast** [feature-sliced/steiger#31]
returns an error:
![image](https://github.com/feature-sliced/steiger/assets/55316571/c14bb0a9-a70d-4823-805d-a47bafc0675a)
but the project has more than one necessary import, for example:
![image](https://github.com/feature-sliced/steiger/assets/55316571/d34a370b-dd53-4086-a5ea-c0b821e06176)

reproduced on windows 10

configuration used:
[tsconfig.json](https://github.com/user-attachments/files/15754185/tsconfig.json)

path of the file importing utilities from entities/conference:
src/widgets/messenger-chat\ui\ChatHeader\ConferenceMembersIndicator.tsx

**Comment by illright** [comment]
I released a new version, 0.2.0, with fixes for Windows, could you try again please and see if that version works for you?
