### ISSUE TITLE
Feature request: import self-written rules

### ISSUE THREAD

**Issue by noveogroup-amorgunov** [feature-sliced/steiger#35]
Hey. I have a feature request: I want to write rules for my project and i import them via config.

It could look like:

```ts
import { defineConfig } from 'steiger'
import rules from '...'

export default defineConfig({
  preset: [...rules]
})
```

**Comment by illright** [comment]
Also tracked by #27

**Comment by illright** [comment]
Bringing #33 in this discussion, I think a flat config would enable this use case quite elegantly. This is definitely something we want to support, but before we get there, we need to create a toolkit for writing custom rules. The specifics of this toolkit are again to be defined :D it would probably include things like `findAllRecursively`

**Comment by noveogroup-amorgunov** [comment]
> I think a flat config would enable this use case quite elegantly.

I like flat config +1

> This is definitely something we want to support, but before we get there, we need to create a toolkit for writing custom rules

I think https://github.com/feature-sliced/filesystem can provide some helpers to write own rules within the FSD. For another methodologies, I think it will be possible to discuss the next step

**Comment by illright** [comment]
And this is also possible now with Steiger 0.5.0!
