### ISSUE TITLE
Feature request: Add links to files in console

### ISSUE THREAD

**Issue by EliseyMartynov** [feature-sliced/steiger#39]
Привет! В eslint инструментах есть удобная фича перехода по ссылке на файл по подсвеченной проблеме. Очень бы хотелось видеть это в steiger, т.к. это значительно повышает DX.
Сейчас путь до файла в консоли есть, но активной ссылки на этот текст нет. Это вносит определенные неудобства.

**Comment by illright** [comment]
Да, это проблема. Я не знаю пока, как лучше сделать это, потому что некоторые правила ругаются не на один файл, а на несколько, и непонятно, куда линкать. Но ещё не думал об этом, если честно

**Comment by EliseyMartynov** [comment]
Если идти 1 к 1, то если правило ругается на несколько файлов - можно разделить это на три одинаковые ошибки с ссылками на разные файлы

**Comment by illright** [comment]
Here's a rundown of existing rules and what object is the closest point to the error:

- ambiguous-slice-names — the slice folder
- excessive-slicing — layer or slice group
- forbidden-imports — the file that contains the wrong import
- import-locality — the file that contains the wrong import
- inconsistent-naming — layer or slice group
- insignificant-slice — slice 
- no-file-segments — file segment
- no-layer-public-api — layer folder
- no-processes — layer folder
- no-public-api-sidestep — the file that contains the wrong import
- no-reserved-folder-names — reserved folder
- no-segmentless-slices — slice folder
- public-api — slice folder
- repetitive-naming — layer folder
- segments-by-purpose — segment folder
- shared-lib-grouping — shared/lib

So really, only three rules here can be linked to files, most others can only be linked to a folder. That's not a big deal, we can link to folders and Cmd+Click would open them in the file browser sidebar, but it's not ideal

**Comment by illright** [comment]
Released Steiger v0.3.0 with this feature included :)

<img width="1407" alt="image" src="https://github.com/feature-sliced/steiger/assets/15035286/47a1cc2d-f05e-4d29-aaba-23ad7b5253b8">
