### ISSUE TITLE
Feature request: Configure rule of cross-imports

### ISSUE THREAD

**Issue by EliseyMartynov** [feature-sliced/steiger#47]
Мы на проекте пришли к соглашению, что в слое виджетов мы разрешаем кросс-импорты в части композиции верстки (т.е. на уровне ui, а не моделей).
Было бы круто, если бы это можно было настроить в Steiger.

**Comment by illright** [comment]
Duplicate of #33, I think. We will add support for glob-based rule inclusion/exclusion
