### ISSUE TITLE
Add an exception for an index file inside the App layer

### ISSUE THREAD

**Issue by daniilsapa** [feature-sliced/steiger#55]
Right now it reports an error on such a case. But it looks like it should not, because the app layer is the entry point to your application, and it's pretty intuitive that it could have an index.js/ts file.

<img width="1055" alt="Screenshot 2024-07-13 at 23 35 16" src="https://github.com/user-attachments/assets/5c01373b-97ac-45bb-b4eb-476847a9a5f0">

**Comment by illright** [comment]
Why not `app/entrypoint`?

**Comment by daniilsapa** [comment]
@illright 
Just my personal opinion on this point.

### 1. How do the users usually name their entry point file?
I reviewed examples from [FSD examples page](https://feature-sliced.design/examples) to see what people usually use.

The results are:
- 32 projects
- 3 do not really meet the FSD structure, so I didn’t count them
- 18 have index.js/ts in the App layer
- 11 have entry files of other names

So, the users tend to have index files there.

### 2. Unnecessary limitation

I understand that an architectural approach for software is partially about well-thought restrictions that you create for yourself that help you structure things. But I personally believe that restrictions should be applied where they are critical, and should not create additional headaches where they are absolutely unnecessary.

### 3. Resistance to integration

When you see an error from your linter, it takes time to understand what is wrong and why. Then you need to decide what to do. In the case we’re discussing, it can be renaming the file or disabling the rule.

This project is still in its early stages so far and I think it is worth reducing resistance to integration as much as possible and the number of such small headaches to a minimum to grow the user base quicker. The more such small things that can annoy users the more chance that another such a small thing can be the last straw where a user decides to abandon/disable the tool.

If this still doesn't sound convincing, feel free to close the issue.

**Comment by illright** [comment]
No, these are good points. Besides, this is not the first time we make exceptions for the App layer. I'm convinced, we can add this exception. Feel free to make another PR :)

**Comment by daniilsapa** [comment]
Got it, sure, I'll add logic to handle this exception and make a PR soon 👌
