### ISSUE TITLE
Throw an exception if a non-existent folder is provided as an FSD root.

### ISSUE THREAD

**Issue by daniilsapa** [feature-sliced/steiger#58]
Right now it just says that no problems were found. But it seems the tool should exit with an error in this case, so the user can understand that they misconfigured the tool early.

<img width="304" alt="Screenshot 2024-07-16 at 19 59 55" src="https://github.com/user-attachments/assets/6804a7d4-407f-4693-8a8f-61ba3a5047c9">

**Comment by illright** [comment]
Indeed, that should be fixed! Ideally, we would also scan the folders around a given path in case it's a typo of 1-2 characters, and we could offer a suggestion to auto-correct the path

**Comment by daniilsapa** [comment]
Yes, I like the idea of scanning the folders and suggesting corrections to the path. It would be convenient and would improve DX. But I think it's a nice-to-have at the project's current stage. I propose to go with throwing the error first and simultaneously create an issue for the auto-correction enhancement, so we can revisit it later when more high-priority tasks are done.

**Comment by illright** [comment]
Upgrading the priority of this because it's very easy to build, yet will help out people who are trying to set up Steiger in their own projects

**Comment by illright** [comment]
Btw, issue #40 is already tracking the auto-detection, I'll link it for context
