### ISSUE TITLE
[shared-lib-grouping] Need option to ignore some entries

### ISSUE THREAD

**Issue by yethee** [feature-sliced/steiger#63]
Currently, there is a false positive violation of the rule when test files are in the same directory.

```
┌ src\shared\lib
✘ Shared/lib has 17 modules, which is above the recommended threshold of 15. Consider grouping them.
│
└ shared-lib-grouping (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/shared-lib-grouping​)
```

![image](https://github.com/user-attachments/assets/bf4177f0-a260-45a8-aa71-564dbd6fa5bf)

**Comment by illright** [comment]
Hi, thanks for reporting. Yes, it makes sense to configure exclusion for test files. We're planning to accomplish this with a new config file format, the RFC is available here. Would this work for you?

https://github.com/feature-sliced/steiger/discussions/53

**Comment by illright** [comment]
This is possible now with Steiger 0.5.0 :)
