### ISSUE TITLE
Implement inclusion/exclusion operators on a VFS

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#66]
It should be a pure function that accepts a `Folder` object and a set of `include`/`exclude` globs that then produces a new `Folder` object that is a subset of the original (without modifying the original)

**Comment by daniilsapa** [comment]
@illright 
Hi, could you assign this task to me?

**Comment by daniilsapa** [comment]
Hi @illright 
I started by looking at the scope of work for this task: what exactly needs to be done and the potential impact on code modules, etc.

This task implies implementing the logic for handling `files` and `ignores` globs, right?

Here I listed possible setting combinations and values for `files` and `ignores`. I just want to make sure that I understand everything correctly and we're on the same page.

So... 

```javascript
const possibleCombinations = [

  // ignore all __mocks__ directories for all rules
  [
    ...fsd.configs.recommended,
    {
      ignores: ['**/__mocks__/**'],
    },
  ],


  // disable public-api rule only for ./src/shared/** folder
  [
    ...fsd.configs.recommended,
    {
      files: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'off',
      },
    },
  ],


  // enable errors for public-api rule only for ./src/shared/** folder
  [
    ...fsd.configs.recommended,
    {
      files: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'error',
      },
    },
  ],


  // disable public-api rule for all folders except ./src/shared/**
  [
    ...fsd.configs.recommended,
    {
      ignores: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'off',
      },
    },
  ],


  // enable errors for public-api rule for all folders except ./src/shared/**
  [
    ...fsd.configs.recommended,
    {
      ignores: ['./src/shared/**'],
      rules: {
        'fsd/public-api': 'error',
      },
    },
  ],
]
```

```javascript
const possibleGlobValues = [
  // all files and subfolders in ./src/shared
  './src/shared/**',

  // All __mock__ directories in all subfolders
  '**/__mocks__/**',

  // specific Button.tsx file
  './src/shared/ui/Button/Button.tsx',

  // all files that have .stories.tsx extension
  '**/*.stories.tsx',
];
```
Am I right?

**Comment by illright** [comment]
Almost, here's how I envisioned it:
- **enable errors for public-api rule only for `./src/shared/**` folder**
  To do that, you would select all files except for `./src/shared/**` and _disable_ the rule there, like your example of `// disable public-api rule for all folders except ./src/shared/**`:
  ```ts
  [
    ...fsd.configs.recommended,
    { ignores: ['./src/shared/**'], rules: { `fsd/public-api': 'off' } },
  ]
  ```
  The reason I prefer this approach over what you suggested is because, in my opinion, they merge better. Essentially, we want to create a list of rule severities "for every file" (we would optimize it, of course), and your proposed configuration reads to me as _"enable all rules with severity 'error' for all files; then, for files in `src/shared`, enable 'fsd/public-api' with severity 'error'"_, and essentially this last part doesn't change anything, because that rule is already enabled with 'error' severity for all files, including `src/shared`
- **enable errors for public-api rule for all folders except `./src/shared/**`**
  In the same way, I think we should instead select all files in `src/shared` and _disable_ the rule there, since the recommended config already enabled it for all files
  
The rest is correct, yes. If you don't have `files` in a config object, it is assumed that `files: '**/*'`. If you don't have `ignores`, it is assumed that all files in `files` are selected. If you don't have `rules`, it is assumed that all enabled rules are chosen. Ultimately, we're following the ESLint conventions outlined here: https://eslint.org/docs/latest/use/configure/configuration-files#specifying-files-and-ignores

**Comment by illright** [comment]
Note that you don't necessarily have to integrate that inclusion/exclusion operator in this task, you can just create the operator itself, and we will make another task to integrate it

**Comment by daniilsapa** [comment]
Thanks for providing that article from the ESLint docs. I've never really delved deep into how the globs there work, so reviewing it came in very handy! I missed 2 possible cases that the article covered.

1. When both `files` and `ignores` are present in the same config object
2. Negation patterns like  `"!**/eslint.config.js"` in `ignores: ["**/*.config.js", "!**/eslint.config.js"],`

So, the question is should we support them right away?

![Screenshot 2024-08-04 at 22 42 29](https://github.com/user-attachments/assets/071b4a6b-f8c9-4259-ba59-ee35c1f99078)

**Comment by illright** [comment]
Yeah, I think we should support them. Shouldn't be a problem, because I expect that most glob libraries already support this
