### ISSUE TITLE
Make the rule set configurable with plugins

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#67]
Currently, the default ruleset is hard-coded. Refactor the FSD plugin to instead export a plugin (see https://github.com/feature-sliced/steiger/discussions/53#discussioncomment-9980110 for the type definition) and make Steiger register rules from plugins.

Make sure to alert about collisions in rule names — they must be unique. To that end, rename all existing rules in the FSD plugin to include an `fsd/` prefix in the rule name.

The default config should include the FSD plugin and enable all of its rules. Create `configs.recommended` with all rules enabled

**Comment by daniilsapa** [comment]
@illright 

Could you assign this task to me?

Also, is it reasonable to release what we've added in the last two weeks? Because it looks like this configuration epic will take some time

**Comment by illright** [comment]
@daniilsapa done. As for releasing — sure, once we merge your PR, we can release
