### ISSUE TITLE
Public API for shared/lib

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#76]
The `no-public-api-sidestep` rule should consider the specifics of `shared/lib` — its public API should be one layer deeper, in `shared/lib/*/index`

**Comment by conarti** [comment]
Is this also correct for `shared/ui`?

Also I think this rule doesn't need to check `shared/assets` as it can contain images, fonts, styles with direct import to `app`'s `main.ts`. Also in my projects it has svg icons folder that automatically compiles into framework components by vite/webpack

**Comment by illright** [comment]
> Is this also correct for shared/ui?

I think we should allow both `shared/ui/index` and `shared/*/index`, but it has to be one or the other.

> Also I think this rule doesn't need to check shared/assets

I don't think this should be part of the rule, I'd rather let users exclude that folder entirely
