### ISSUE TITLE
Cross-imports not defined

### ISSUE THREAD

**Issue by EgorEast** [feature-sliced/steiger#85]
Cross-imports are not defined, although the plugin for eslint defines a lot. 

Reproduced on windows

Import: 
`import { useAddMemberMutation } from 'features/edit-member-list'`

Path of the file that imports:
`src\shared\lib\contact-cell\useAddToMembers.ts`

Aliases in tsconfig:
`{
  "app": ["src/app"],
  "app/*": ["src/app/*"],
  "entities/*": ["src/entities/*"],
  "features/*": ["src/features/*"],
  "pages/*": ["src/pages/*"],
  "shared/*": ["src/shared/*"],
  "widgets/*": ["src/widgets/*"],
  ...
}`

Base url: `"baseUrl": ".",`

The config is described in the file `config.app.json`, which is connected in tsconfig.json like this: `"references": [{ "path": "./config.app.json" }, { "path": "./tsconfig.node.json" }]`

**Comment by illright** [comment]
Yeah, I was suspecting that it might be the same issue as #78. I'll close this to remove duplicates, but rest assured that this is going to be fixed soon. 

As a workaround, you can duplicate the alias information into the main tsconfig for now, I'll let you know once this issue is fixed.
