### ISSUE TITLE
Add information about the new config structure to README.md

### ISSUE THREAD

**Issue by daniilsapa** [feature-sliced/steiger#89]
- Description of the new config format
- How to use the new config
- A short guide to migration to the new config

The migration guide should contain commands to perform migration for the major package managers:
- npm
- yarn
- pnpm

**Comment by daniilsapa** [comment]
@illright 
Could you assign this one to me?

**Comment by illright** [comment]
Sure. One comment before you start — I would prefer to keep migration instructions in a separate `MIGRATION_GUIDE.md` rather than the README, and the README could simply link there.
