### ISSUE TITLE
References to features aren't detected in a Nuxt setup

### ISSUE THREAD

**Issue by illright** [feature-sliced/steiger#94]
Repro: ~~https://github.com/SVBadSeed/nuxt-steiger~~ https://github.com/feature-sliced/nuxt-steiger

```
┌ src/features/session/register
✘ This slice has no references. Consider removing it.
│
└ insignificant-slice (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/insignificant-slice​)

┌ src/features/session/logout
✘ This slice has no references. Consider removing it.
│
└ insignificant-slice (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/insignificant-slice​)

┌ src/features/session/login
✘ This slice has no references. Consider removing it.
│
└ insignificant-slice (​https://github.com/feature-sliced/steiger/tree/master/packages/steiger-plugin-fsd/src/insignificant-slice​)
```

There is a reference to these slices in `src/pages/home/ui/home.vue`

**Comment by illright** [comment]
I noticed that the author of the reproduction deleted their repo, so I recreated this issue and updated the repro repo link

**Comment by daniilsapa** [comment]
@illright 
I'll check if this newly discovered edge case is fixed with my updates

**Comment by daniilsapa** [comment]
@illright 
I noticed a bug while checking that edge case. I already know how to fix that and will fix it by the end of the day
